# Generated by Django 5.1.6 on 2025-04-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Empname", models.CharField(max_length=50)),
                ("Empid", models.IntegerField()),
                ("Empdept", models.CharField(max_length=20)),
                ("Address", models.TextField()),
            ],
        ),
    ]
